package com.twitter.tweet_mixer.utils

object CandidatePipelineConstants {
  val PopularGeoTweets = "PopularGeoTweets"
  val PopGrokTopicTweets = "PopGrokTopicTweets"
  val PopularTopicTweets = "PopularTopicTweets"
  val CertoTopicTweets = "CertoTopicTweets"
  val SkitTopicTweets = "SkitTopicTweets"
  val SkitHighPrecisionTopicTweets = "SkitHighPrecisionTopicTweets"
  val LocalTweets = "LocalTweets"
  val SimClustersInterestedIn = "SimClustersInterestedIn"
  val SimClustersProducerBased = "SimClustersProducerBased"
  val SimClustersTweetBased = "SimClustersTweetBased"
  val SimClustersPromotedCreator = "SimClustersPromotedCreator"
  val Trends = "Trends"
  val Events = "Events"
  val TrendsVideo = "TrendsVideo"
  val TwhinConsumerBased = "TwhinConsumerBased"
  val TwhinRebuildUserTweetSimilarity = "TwhinRebuildUserTweetSimilarity"
  val TwhinRebuildTweetSimilarity = "TwhinRebuildTweetSimilarity"
  val TwhinTweetSimilarity = "TwhinTweetSimilarity"
  val RelatedCreator = "RelatedCreator"
  val RelatedNsfwCreator = "RelatedNsfwCreator"
  val UserLocation = "UserLocation"
  val UTEG = "UTEG"
  val UTGExpansionTweetBased = "UTGExpansionTweetBased"
  val UTGTweetBased = "UTGTweetBased"
  val UTGProducerBased = "UTGProducerBased"
  val UVGExpansionTweetBased = "UVGExpansionTweetBased"
  val UVGTweetBased = "UVGTweetBased"
  val EarlybirdInNetwork = "EarlybirdInNetwork"
  val EarlybirdAuthorBased = "EarlybirdAuthorBased"
  val EvergreenVideos = "EvergreenVideos"
  val DeepRetrievalUserTweetSimilarity = "DeepRetrievalUserTweetSimilarity"
  val DeepRetrievalTweetTweetSimilarity = "DeepRetrievalTweetTweetSimilarity"
  val DeepRetrievalTweetTweetEmbeddingSimilarity = "DeepRetrievalTweetTweetEmbeddingSimilarity"
  val ContentExplorationDRTweetTweet = "ContentExplorationDRTweetTweet"
  val ContentExplorationEvergreenDRTweetTweet = "ContentExplorationEvergreenDRTweetTweet"
  val ContentExplorationDRTweetTweetTierTwo = "ContentExplorationDRTweetTweetTierTwo"
  val ContentExplorationDRUserTweet = "ContentExplorationDRUserTweet"
  val ContentExplorationDRUserTweetTierTwo = "ContentExplorationDRUserTweetTierTwo"
  val ContentExplorationEmbeddingSimilarity = "ContentExplorationEmbeddingSimilarity"
  val ContentExplorationEmbeddingSimilarityTierTwo = "ContentExplorationEmbeddingSimilarityTierTwo"
  val ContentExplorationSimclusterColdPosts = "ContentExplorationSimclusterColdPosts"
  val UserInterestSummary = "UserInterestSummary"
  val EvergreenDRUserTweet = "EvergreenDRUserTweet"
  val EvergreenDRCrossBorderUserTweet = "EvergreenDRCrossBorderUserTweet"
  val MediaDeepRetrievalTweetTweetSimilarity = "MediaDeepRetrievalTweetTweetSimilarity"
  val MediaDeepRetrievalUserTweetSimilarity = "MediaDeepRetrievalUserTweetSimilarity"
  val MediaEvergreenDeepRetrievalUserTweetSimilarity =
    "MediaEvergreenDRUserTweetSimilarity"
  val MediaPromotedCreatorDeepRetrievalUserTweetSimilarity =
    "MediaPromotedCreatorDRUserTweetSimilarity"
  val ControlAiTopicTweets = "ControlAiTopicTweets"

  val Haplolite = "Haplolite"
  val QigSearchHistoryTweets = "QigSearchHistoryTweets"
  val TwitterClipV0Short = "TwitterClipV0Short"
  val TwitterClipV0Long = "TwitterClipV0Long"
  val SemanticVideo = "SemanticVideo"
  val MemeVideo = "MemeVideo"
  val ContentEmbeddingAnn = "ContentEmbeddingAnn"
  val CuratedUserTlsPerLanguage = "CuratedUserTlsPerLanguage"
}
